### PR TITLE
Client cli

### PR DESCRIPTION
**Pull request by Lone-Coder**

### CODE REVIEW

**Comment by Lone-Coder** [comment]
So what do I need to do to get the AppVeyor build working?

**Comment by Lone-Coder** [comment]
Ehh, what's %secureInfoPassword% suppose to be?

**Comment by Lone-Coder** [comment]
@ebekker Ehh, what's %secureInfoPassword% suppose to be?

**Comment by ebekker** [comment]
@Lone-Coder, the AppVeyor check failed because there are some sensitive files in the test project and they're [encrypted for AV](http://www.appveyor.com/docs/how-to/secure-files) to use for building and testing.  AV restricts from decrypting during PRs because that would be a potenttial security hole, so the failed AV build is expected for PRs.

**Comment by ebekker** [comment]
So I saw that you started including a pre-built binary in your folder, and I would ask to refrain from doing that.  In general, don't commit anything that is generated or derived from the existing source code, let the build system make those for you, and especially when it's a binary file (object files, assemblies, etc.) or an assembled package.

One of the issues, especially with git is that everyone who clones the repo has a copy of *all* the history of *all* the branches.  Git does a good job of keeping its repo content small by storing only changes, but with binary files, the content changes drastically, so it has to store a lot and that means everyone who has a fork or clone has a lot of content to update.

There are a few good alternatives.  First you can simply create a brand new repo, such as "letsencrypt-win-cli-dist" or whatever you like and just use it to commit prebuilt binaries for distribution.  Be careful though because you can quickly run against the **soft** 1GB quota that [github recommends](https://help.github.com/articles/what-is-my-disk-quota/) because of the difficulty in storing deltas with binaries that I talked about above.

The other, much better atlernative, is to use GitHub's own facility for such things, namely [releases] (https://help.github.com/articles/about-releases/).  With releases, you declare a point in your code base that's stable enough for use, you can add any release notes that you want, and you can attach any pre-built binaries for easy access.

**Comment by ebekker** [comment]
I will review the PR shortly and merge it in, in general I'm only going to look for any blatant issues or just make suggestions, but I'm planning on letting you *own* the CLI piece.  In the mean time, you may want to see if you can try to [remove the .zip file history](https://help.github.com/articles/removing-files-from-a-repository-s-history/) just to clean up the source code.

**Comment by Lone-Coder** [comment]
Okay. I think I killed the zip file history correctly. Can you add a building of an artifact for the CLI client to AppVeyor for me?

**Pull request closed without merging**
